project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://samanthacsik.github.io/
  # cookie-consent: 
  #   type: express 
  #   style: headline
  #   palette: dark
  favicon: images/chick.png
  google-analytics: 
    tracking-id: "G-LW03VL0YTS" #"UA-242992767-1"
    anonymize-ip: true
  # title: "samantha csik"
  navbar:
    title: false
    logo: images/logos/logo-dark.png
    logo-alt: "The name 'sam csik' written in green text. Above 'csik' is a dark green horizontal line, above which sits a green chick icon."
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - href: talks_workshops.qmd
        text: talks & workshops
      - href: projects.qmd
        text: projects
      - posts.qmd
      - resources.qmd
      - href: CV/SCsik_CV.pdf
        text: cv
        target: _blank
      - icon: github
        href: https://github.com/samanthacsik/samanthacsik.github.io
        target: _blank
      - icon: twitter
        href: https://twitter.com/SamanthaCsik
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/samanthacsik/
        target: _blank
      - icon: envelope
        href: mailto:scsik@ucsb.edu
  page-footer: 
    background: light
    left: Copyright 2021, Samantha Csik
    right: This website is built with {{< fa heart title="a heart" >}}, {{< fa brands r-project title="R Project" >}} and [Quarto](https://quarto.org/)
    # right: 
    #   - icon: github
    #     href: https://github.com/samanthacsik
    #   - icon: twitter
    #     href: https://twitter.com/SamanthaCsik
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/samanthacsik/
    #   - icon: envelope
    #     href: mailto:scsik@ucsb.edu
  # reader-mode: true
  # repo-url: https://github.com/samanthacsik/samanthacsik-quarto-website
  # repo-actions: [edit, issue]

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    # css: styles.css
    mainfont: Nunito
    toc: true


